version: '3'

services:
  bot:
    build: .
    volumes:
      - .:/bot
    environment:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"